name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 8
      - name: Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew clean shadowJar --no-daemon --stacktrace
      - name: Find and rename artifact
        run: |
          mkdir -p output
          cp build/libs/Yuri.jar output/Yuri.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Yuri
          path: output/Yuri.jar